# Generated by Django 3.2.7 on 2021-09-06 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_rest_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='offer',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
