# Generated by Django 3.2.7 on 2021-09-06 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_rest_api', '0002_auto_20210906_1739'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={},
        ),
    ]
